[package]
name = "lush-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lush"
path = "lush.rs"

[dependencies]
midir = "0.8.0"
cpal = "0.13.5"
clap = { version = "3.2.5", features = ["derive"] }
anyhow = "1.0.58"